# Generated by Django 5.1.6 on 2025-02-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('brithdate', models.IntegerField()),
                ('created_ed', models.DateTimeField(auto_now_add=True)),
                ('update_ed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('horsepower', models.IntegerField()),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('context', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('created_ed', models.DateTimeField(auto_now_add=True)),
                ('update_ed', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.carmodel')),
            ],
            options={
                'verbose_name': 'CAR',
                'verbose_name_plural': 'CARS',
                'ordering': ['-created_ed'],
            },
        ),
    ]
